const EXAMPLE_ONE = {
  UPDATE: 'ONE_UPDATE',
  NEXT_PAGE: 'ONE_NEXT_PAGE',
  PREVIOUS_PAGE: 'ONE_PREVIOUS_PAGE',
  LOADING: 'ONE_LOADING',
  LOADED: 'ONE_LOADED',
  ERROR: 'ONE_ERROR'
}

export { EXAMPLE_ONE }