const EXAMPLE_ONE = {
  UPDATE: 'ONE_UPDATE',
  NEXT_PAGE: 'ONE_NEXT_PAGE',
  PREVIOUS_PAGE: 'ONE_PREVIOUS_PAGE',
  LOADING: 'ONE_LOADING',
  LOADED: 'ONE_LOADED',
  ERROR: 'ONE_ERROR'
}

const EXAMPLE_TWO = {
  SET_MOVIE: 'SET_MOVIE',
  UPDATE: 'TWO_UPDATE',
  NEXT_PAGE: 'TWO_NEXT_PAGE',
  LOADING: 'TWO_LOADING',
  LOADED: 'TWO_LOADED',
  ERROR: 'TWO_ERROR'
}

export { EXAMPLE_ONE, EXAMPLE_TWO }